name: Daily Forecast Update

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10 AM UTC (6 AM ET)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run forecast generator
      run: python forecast_generator.py
    - name: Commit and push
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add forecast.png
        git commit -m 'Daily forecast update'
        git push
