name: Update Sunrise Graphic

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 4:00 AM EDT (8:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Pillow
        run: pip install pillow requests

      - name: Generate Sunrise Graphic
        run: python generate_sunrise_graphic.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sunrise.png
          git commit -m "Daily sunrise update"
          git push
