name: Generate Sunrise Graphic

on:
  schedule:
    - cron: '10 10 * * *'  # 6:10 AM ET
  workflow_dispatch:       # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pillow dropbox requests pytz

      - name: Generate Sunrise Graphic
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        run: python generate_sunrise_graphic.py
